services:
  config_saver:
    container_name: config_saver
    build: .
    env_file: .env
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_CONFIGS_COLLECTION=${MONGO_CONFIGS_COLLECTION}
    depends_on:
      - mongo
      - builder
    ports:
      - "${SERVER_PORT}:${HOST_PORT}"

  builder:
    image: builder
    build:
      context: .
      dockerfile: Dockerfile.build
    depends_on:
      - system

  system:
    image: system
    build:
      context: .
      dockerfile: Dockerfile.system

  mongo:
    container_name: mongo
    image: mongo:8
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: